<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Pekerjaan;

class PekerjaanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pekerjaanData = [
            ['nama_pekerjaan' => 'Belum/Tidak Bekerja'],
            ['nama_pekerjaan' => 'Mengurus Rumah Tangga'],
            ['nama_pekerjaan' => 'Pelajar/Mahasiswa'],
            ['nama_pekerjaan' => 'Pensiunan'],
            ['nama_pekerjaan' => 'Wiraswasta'],
            ['nama_pekerjaan' => 'Swasta'],
            ['nama_pekerjaan' => 'PNS (Pegawai Negeri Sipil)'],
            ['nama_pekerjaan' => 'TNI (Tentara Nasional Indonesia)'],
            ['nama_pekerjaan' => 'POLRI'],
            ['nama_pekerjaan' => 'Karyawan Swasta'],
            ['nama_pekerjaan' => 'Karyawan BUMN'],
            ['nama_pekerjaan' => 'Karyawan BUMD'],
            ['nama_pekerjaan' => 'Karyawan Honorer'],
            ['nama_pekerjaan' => 'Buruh Harian Lepas'],
            ['nama_pekerjaan' => 'Buruh Tani/Perkebunan'],
            ['nama_pekerjaan' => 'Buruh Nelayan/Perikanan'],
            ['nama_pekerjaan' => 'Buruh Peternakan'],
            ['nama_pekerjaan' => 'Pembantu Rumah Tangga'],
            ['nama_pekerjaan' => 'Tukang Cukur'],
            ['nama_pekerjaan' => 'Tukang Listrik'],
            ['nama_pekerjaan' => 'Tukang Batu'],
            ['nama_pekerjaan' => 'Tukang Kayu'],
            ['nama_pekerjaan' => 'Tukang Sol Sepatu'],
            ['nama_pekerjaan' => 'Tukang Las/Pandai Besi'],
            ['nama_pekerjaan' => 'Tukang Jahit'],
            ['nama_pekerjaan' => 'Tukang Gigi'],
            ['nama_pekerjaan' => 'Penata Rambut'],
            ['nama_pekerjaan' => 'Penata Rias'],
            ['nama_pekerjaan' => 'Mekanik'],
            ['nama_pekerjaan' => 'Sopir'],
            ['nama_pekerjaan' => 'Montir'],
            ['nama_pekerjaan' => 'Pedagang'],
            ['nama_pekerjaan' => 'Petani'],
            ['nama_pekerjaan' => 'Peternak'],
            ['nama_pekerjaan' => 'Nelayan'],
            ['nama_pekerjaan' => 'Industri Rumah Tangga'],
            ['nama_pekerjaan' => 'Pengrajin'],
            ['nama_pekerjaan' => 'Seniman'],
            ['nama_pekerjaan' => 'Wartawan'],
            ['nama_pekerjaan' => 'Ustadz/Mubaligh'],
            ['nama_pekerjaan' => 'Juru Masak'],
            ['nama_pekerjaan' => 'Penjaga Toko'],
            ['nama_pekerjaan' => 'Penjaga Warung'],
            ['nama_pekerjaan' => 'Pendeta'],
            ['nama_pekerjaan' => 'Pastur'],
            ['nama_pekerjaan' => 'Perawat'],
            ['nama_pekerjaan' => 'Bidan'],
            ['nama_pekerjaan' => 'Dokter'],
            ['nama_pekerjaan' => 'Apoteker'],
            ['nama_pekerjaan' => 'Psikiater'],
            ['nama_pekerjaan' => 'Psikolog'],
            ['nama_pekerjaan' => 'Guru'],
            ['nama_pekerjaan' => 'Dosen'],
            ['nama_pekerjaan' => 'Tenaga Pengajar'],
            ['nama_pekerjaan' => 'Konsultan'],
            ['nama_pekerjaan' => 'Notaris'],
            ['nama_pekerjaan' => 'Pengacara'],
            ['nama_pekerjaan' => 'Hakim'],
            ['nama_pekerjaan' => 'Jaksa'],
            ['nama_pekerjaan' => 'Arsitek'],
            ['nama_pekerjaan' => 'Akuntan'],
            ['nama_pekerjaan' => 'Desainer'],
            ['nama_pekerjaan' => 'Manajer'],
            ['nama_pekerjaan' => 'Direktur'],
            ['nama_pekerjaan' => 'Programmer'],
            ['nama_pekerjaan' => 'Analis Sistem'],
            ['nama_pekerjaan' => 'Teknisi'],
            ['nama_pekerjaan' => 'Wakil Gubernur'],
            ['nama_pekerjaan' => 'Gubernur'],
            ['nama_pekerjaan' => 'Wakil Bupati'],
            ['nama_pekerjaan' => 'Bupati'],
            ['nama_pekerjaan' => 'Anggota DPRD Provinsi'],
            ['nama_pekerjaan' => 'Anggota DPRD Kabupaten'],
            ['nama_pekerjaan' => 'Tenaga Tata Usaha'],
            ['nama_pekerjaan' => 'Editor'],
            ['nama_pekerjaan' => 'Penulis'],
            ['nama_pekerjaan' => 'Penyiar'],
            ['nama_pekerjaan' => 'Presenter'],
            ['nama_pekerjaan' => 'Peneliti'],
            ['nama_pekerjaan' => 'Fotografer'],
            ['nama_pekerjaan' => 'Videografer'],
            ['nama_pekerjaan' => 'Duta Besar'],
            ['nama_pekerjaan' => 'Waiter/Waitress'],
            ['nama_pekerjaan' => 'Biarawati'],
            ['nama_pekerjaan' => 'Satpam'],
            ['nama_pekerjaan' => 'Petugas Kebersihan'],
            ['nama_pekerjaan' => 'Pramugari/Pramugara'],
            ['nama_pekerjaan' => 'Masinis'],
            ['nama_pekerjaan' => 'Pilot'],
            ['nama_pekerjaan' => 'Nahkoda'],
            ['nama_pekerjaan' => 'ABK (Anak Buah Kapal)'],
            ['nama_pekerjaan' => 'Penerjemah'],
            ['nama_pekerjaan' => 'Pemandu Wisata'],
            ['nama_pekerjaan' => 'Travel Agent'],
            ['nama_pekerjaan' => 'Pegawai Bank'],
            ['nama_pekerjaan' => 'Pegawai Asuransi'],
            ['nama_pekerjaan' => 'Pegawai Pajak'],
            ['nama_pekerjaan' => 'Pegawai Bea Cukai'],
            ['nama_pekerjaan' => 'Pegawai Imigrasi'],
            ['nama_pekerjaan' => 'Pegawai Perusahaan Startup'],
            ['nama_pekerjaan' => 'Asisten Ahli'],
            ['nama_pekerjaan' => 'Promotor Acara'],
            ['nama_pekerjaan' => 'Anggota Lembaga Tinggi'],
            ['nama_pekerjaan' => 'Investor'],
            ['nama_pekerjaan' => 'Lainnya'],
        ];

        foreach ($pekerjaanData as $data) {
            Pekerjaan::create($data);
        }
    }
}
