<?php

namespace App\Http\Controllers\Api;

use App\Http\Requests\Srt\StoreSrtJenisSuratRequest;
use App\Http\Requests\Srt\UpdateSrtJenisSuratRequest;
use App\Models\SrtJenisSurat;
use App\Models\SrtJenisSuratPenduduk;
use App\Services\DocumentConverter;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;

class SrtJenisSuratController extends ApiController
{
    protected int $defaultPerPage = 20;
    protected int $maxPerPage = 100;

    public function index(Request $request): JsonResponse
    {
        $perPage = min((int) $request->input('per_page', $this->defaultPerPage), $this->maxPerPage);

        $records = SrtJenisSurat::with(['srtKategoriSurat', 'srtJenisSuratPenduduks'])
            ->latest()
            ->paginate($perPage);

        return $this->success($records);
    }

    public function store(StoreSrtJenisSuratRequest $request): JsonResponse
    {
        try {
            $result = DB::transaction(function () use ($request) {
                $data = $request->only([
                    'kategori_surat_id',
                    'kode_jenis_surat',
                    'nama_jenis_surat',
                    'deskripsi',
                    'is_active',
                ]);

                // Handle template file upload
                if ($request->hasFile('template')) {
                    // Store the docx template
                    $data['template_path'] = $request->file('template')
                        ->store('templates', 'public');

                    // Convert docx to PDF using LibreOffice
                    $fullDocxPath = Storage::disk('public')->path($data['template_path']);
                    $pdfDir = 'templates_pdf';
                    File::ensureDirectoryExists(Storage::disk('public')->path($pdfDir));

                    $converter = new DocumentConverter();
                    $pdfFullPath = $converter->docxToPdf($fullDocxPath);

                    // Move/copy the generated PDF to the public storage templates_pdf directory
                    $pdfFilename = pathinfo($data['template_path'], PATHINFO_FILENAME) . '.pdf';
                    $pdfStoragePath = $pdfDir . '/' . $pdfFilename;

                    if (file_exists($pdfFullPath)) {
                        Storage::disk('public')->put($pdfStoragePath, file_get_contents($pdfFullPath));
                        $data['template_pdf_path'] = $pdfStoragePath;
                        // Clean up the temp PDF generated by LibreOffice (it's in generated_surat/pdf)
                        @unlink($pdfFullPath);
                    }
                }

                $jenisSurat = SrtJenisSurat::create($data);

                // Create SrtJenisSuratPenduduk records
                if ($request->has('penduduk_fields')) {
                    $pendudukFields = $request->input('penduduk_fields', []);
                    foreach ($pendudukFields as $field) {
                        $jenisSurat->srtJenisSuratPenduduks()->create([
                            'urutan' => $field['urutan'],
                            'kode' => $field['kode'],
                            'label' => $field['label'],
                            'deskripsi' => $field['deskripsi'] ?? null,
                            'wajib' => $field['wajib'] ?? true,
                        ]);
                    }
                }

                return $jenisSurat;
            });

            return $this->success(
                $result->load(['srtKategoriSurat', 'srtJenisSuratPenduduks']),
                'Jenis surat berhasil ditambahkan.',
                201
            );
        } catch (\Throwable $e) {
            return $this->error(
                'Gagal menyimpan jenis surat: ' . $e->getMessage(),
                null,
                500
            );
        }
    }

    public function show(string $id): JsonResponse
    {
        $jenisSurat = SrtJenisSurat::with([
            'srtKategoriSurat',
            'srtJenisSuratPenduduks',
        ])->findOrFail($id);

        return $this->success($jenisSurat);
    }

    // public function show(string $id): JsonResponse
    // {
    //     $jenisSurat = $this->modelClass::with([
    //         'srtKategoriSurat',
    //         'srtJenisSuratPenduduks',
    //     ])->findOrFail($id);

    //     return response()->json(
    //         [
    //             'jenis_surat' => $jenisSurat,
    //         ]
    //     );
    // }


    public function update(UpdateSrtJenisSuratRequest $request, string $id): JsonResponse
    {
        $record = SrtJenisSurat::findOrFail($id);

        try {
            DB::transaction(function () use ($request, $record) {
                $data = $request->only([
                    'kategori_surat_id',
                    'kode_jenis_surat',
                    'nama_jenis_surat',
                    'deskripsi',
                    'is_active',
                ]);

                // Handle template file upload — delete old files if exists
                if ($request->hasFile('template')) {
                    // Delete old docx template
                    if ($record->template_path && Storage::disk('public')->exists($record->template_path)) {
                        Storage::disk('public')->delete($record->template_path);
                    }
                    // Delete old pdf template
                    if ($record->template_pdf_path && Storage::disk('public')->exists($record->template_pdf_path)) {
                        Storage::disk('public')->delete($record->template_pdf_path);
                    }

                    // Store the new docx template
                    $data['template_path'] = $request->file('template')
                        ->store('templates', 'public');

                    // Convert docx to PDF using LibreOffice
                    $fullDocxPath = Storage::disk('public')->path($data['template_path']);
                    $pdfDir = 'templates_pdf';
                    File::ensureDirectoryExists(Storage::disk('public')->path($pdfDir));

                    $converter = new DocumentConverter();
                    $pdfFullPath = $converter->docxToPdf($fullDocxPath);

                    // Move/copy the generated PDF to the public storage templates_pdf directory
                    $pdfFilename = pathinfo($data['template_path'], PATHINFO_FILENAME) . '.pdf';
                    $pdfStoragePath = $pdfDir . '/' . $pdfFilename;

                    if (file_exists($pdfFullPath)) {
                        Storage::disk('public')->put($pdfStoragePath, file_get_contents($pdfFullPath));
                        $data['template_pdf_path'] = $pdfStoragePath;
                        // Clean up the temp PDF generated by LibreOffice
                        @unlink($pdfFullPath);
                    }
                }

                $record->update($data);

                // Sync SrtJenisSuratPenduduk records: delete all, then re-create
                if ($request->has('penduduk_fields')) {
                    $record->srtJenisSuratPenduduks()->delete();

                    $pendudukFields = $request->input('penduduk_fields', []);
                    foreach ($pendudukFields as $field) {
                        $record->srtJenisSuratPenduduks()->create([
                            'urutan' => $field['urutan'],
                            'kode' => $field['kode'],
                            'label' => $field['label'],
                            'deskripsi' => $field['deskripsi'] ?? null,
                            'wajib' => $field['wajib'] ?? true,
                        ]);
                    }
                }
            });

            return $this->success(
                $record->fresh()->load(['srtKategoriSurat', 'srtJenisSuratPenduduks']),
                'Jenis surat berhasil diperbarui.'
            );
        } catch (\Throwable $e) {
            return $this->error(
                'Gagal memperbarui jenis surat: ' . $e->getMessage(),
                null,
                500
            );
        }
    }

    public function destroy(string $id): JsonResponse
    {
        $record = SrtJenisSurat::with('srtJenisSuratPenduduks')->findOrFail($id);

        try {
            DB::transaction(function () use ($record) {
                // Delete template files if exists
                if ($record->template_path && Storage::disk('public')->exists($record->template_path)) {
                    Storage::disk('public')->delete($record->template_path);
                }
                if ($record->template_pdf_path && Storage::disk('public')->exists($record->template_pdf_path)) {
                    Storage::disk('public')->delete($record->template_pdf_path);
                }

                // Delete related penduduk fields
                $record->srtJenisSuratPenduduks()->delete();

                // Delete the record itself
                $record->delete();
            });

            return $this->success(
                null,
                'Jenis surat berhasil dihapus.'
            );
        } catch (\Throwable $e) {
            return $this->error(
                'Gagal menghapus jenis surat: ' . $e->getMessage(),
                null,
                500
            );
        }
    }
}
